### ISSUE TITLE
gsb http proxy improvements

### ISSUE THREAD

**Issue by staszek-krotki** [golemfactory/ya-runtime-ai#53]
- [x] should not always return a stream, return what is requested based on accept header
    - use GSB streaming only if request accepts streamed response
    - use GSB non-streaming otherwise
- [ ] allow accept encoding (remove from ignored headers list)
- [ ] return http response headers
- [ ] remove unwrap()s
- [x] hide gsb-binding in component
- [ ] support for other http methods (not only GET, POST) 
```[tasklist]
### Tasks
```

Tests were moved to issue: https://github.com/golemfactory/ya-runtime-ai/issues/98
